version: '3.8'
services:
  app:
    build: .
    container_name: nodejs-server
    restart: unless-stopped
    environment:
      MONGO_DB_URI: mongodb://root:123456@103.77.246.57:27017/
      PORT: 3004
      SECRET_KEY_FOR_ACCESS_TOKEN: abcde
      SECRET_KEY_FOR_REFRESH_TOKEN: 1234
      FIREBASE_PROJECT_ID: test-firebase-storage-d1b61
      VNP_TMN_CODE: UJ8LGDF9
      VNP_HASH_SECRET: 1DCNKPUZ6A20KT7GSGA33PM0LOH8W5Z3
      VNP_URL: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      VNP_API: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
      VNP_RETURN_URL: http://localhost:3000/order/vnpay_return
    ports:
      - "3004:3004"